jthegedus/svelte-adapter-firebase

- package.json
Add repo fields, keywords, license, bug link etc to `package.json` so npmjs displays these fields.
Fixes: #3
> docs: repo information to package.json

- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yaml
- .husky/commit-msg
- .husky/pre-commit
- README.md
- codeql workflow
- rename `ci` workflow to `test`
- fix husky git hooks
> chore: codeql and test workflows

- package.json
- pnpm-lock.yaml
- rollup.config.js
- src/cli.js
- src/utils.js
- tests/index.test.js
- tsconfig.json
This PR updates the adapter API to that in `@sveltejs/kit@1.0.0-next.54`
- migrate to commonjs
- include `typescript` and `@sveltejs/kit` deps with `tsconfig.json` for better typing during dev
- improve typings based off of new errors
- fix new errors
> fix: align adapter API with SvelteKit v1.0.0-next.54

- CONTRIBUTING.md
- README.md
> docs: refactor documentation for easier reading

- README.md
- src/index.js
Align docs examples with ESM adapter/SvelteKit syntax.
> docs: algin with esm syntax

- src/utils.js
- tests/index.test.js
Missed this in #48 
Fixes: #44
> fix: resolve dirname of firebaseJsonDir

- .github/workflows/test.yml
Trigger test and integration workflows on push to the `main` branch and on all PR commits.
Fixes: #61
> ci: run test/integration workflows once per commit on PR

- package.json
Fix the assets attached to the GitHub release produced by semantic-release. This was supposed to change back in #39 (`v0.6.0`)
Fixes: #59
> fix: github release assets

- README.md
Explain what the adapter outputs in the README
Fixes: #51
> docs: explain adapter output

- README.md
- general documentation improvements
- show `svelte.config.js` changes as a diff
- link to all adapter options from first example
Fixes: #71
> docs: improve language

- src/index.js
Fixes: #70 
Since this PR is so small, you can probably cherry pick the commit or just copy the changes into #74.
> fix: import call for svelte.config.js on windows

- .github/workflows/test.yml
- src/index.js
- completed in #76 :pray: 
Fixes: #70
> fix: import of svelte.config.js requires string

- README.md
> docs: improve pkgjson instructions

- README.md
Update FAQ regarding SvelteKit endpoints and Firebase JS SDK v9
Fixes: #81
> docs: clarify firebase sdk v9 usage in faq

- commitlint.config.cjs
- package.json
Fewer configs in repo :+1: 
Fixes: #86
> chore: move commitlint config to pkgjson

- README.md
- src/utils.js
- tests/fixtures/failures/cf_multi_site_no_hostingSite_match.json
- tests/fixtures/failures/cr_invalid_serviceId.json
- tests/fixtures/failures/site_empty_public.json
- tests/index.test.js
> fix: improve tests & document tip codes

- src/files/handler.js
> fix: wait request body infinitely in handler.js

- README.md
- src/files/handler.js
Syncs the adapter API with the changes in https://github.com/sveltejs/kit/pull/1804/ where the adapter entrypoint handles the application initialization.
> feat: adapter runs app init

- .github/workflows/release.yaml
- package.json
- pnpm-lock.yaml
Migrate to [release-please](https://github.com/google-github-actions/release-please-action) from [semantic-release](https://semantic-release.gitbook.io/semantic-release/).
Release-please implements a less indrusive "release PR" which grants more control to maintainers about when to release something.
Fixes: Closes #105
> ci: migrate to release-please

- package.json
- pnpm-lock.yaml
Update peer dep and hopefully release #110 and #111
> fix: update sveltekit peer dep

- .github/workflows/release.yaml
- CHANGELOG.md
hopefully release #110 and #111 and #113
> fix: ci release workflow

- .github/workflows/release.yaml
- CHANGELOG.md
Yet another attempt to change release pipeline. Prior failures seem to be around the NPM registry not setting correctly.
> fix: release workflow

- src/index.js
Document potential Cloud Run deprecation as noted in #118. Link to #118 as RFC
> fix: document potential Cloud Run deprecation

- README.md
Thanks for the great repo. I just tried to set it up for the first time and felt necessary to do some suggestions on your starter instructions. Some things that I did not fully pick up - maybe impatience - hopefully it will help others
Fixes: List issue numbers here
> docs: clarify Firebase setup in instructions

- package.json
Export `package.json` in package for tooling to consume.
Fixes: #131
> fix: export package.json from package

- .tool-versions
- fix: e2e tests with latest emulator version
Fixes: #125
> fix: e2e tests with latest emulator

- src/files/entry.d.ts
- src/files/entry.js
- src/files/firebase-to-svelte-kit.js
- src/index.js
Added some changes to follow latest Kit adapter API changes (https://github.com/sveltejs/kit/pull/2931).
This pull request fixes https://github.com/jthegedus/svelte-adapter-firebase/issues/156 problem and it might be fix a part of https://github.com/jthegedus/svelte-adapter-firebase/issues/153 issues.
fixes https://github.com/jthegedus/svelte-adapter-firebase/issues/156
refs https://github.com/jthegedus/svelte-adapter-firebase/issues/153
> fix: reading 'log' error

- .github/workflows/test.yaml
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/files/shims.js
- tests/integration/integration-test.bash
Replace `src/files/shims.js` with the polyfills version.
Fixes: #169
> fix(#169): Replace `installFetch()` with `installPolyfills()`

- .npmrc
- .tool-versions
- README.md
- package.json
- pnpm-lock.yaml
- src/files/shims.js
- src/index.d.ts
- src/index.js
- src/utils.js
- bump sys deps in `.tool-versions`
- bump deps in `package.json`
- fix xojs issues
- `utf-8` -> `utf8`
> fix: bump kit versions, update deps & fix xojs issues

- .github/workflows/test.yaml
- package.json
- pnpm-lock.yaml
- src/files/entry.js
- src/files/firebase-to-svelte-kit.js
- src/index.d.ts
- src/index.js
- tests/end-to-end/scaffold/firebase.json
- tests/end-to-end/test.bash
Reverts jthegedus/svelte-adapter-firebase#201
> chore(revert): Sync with kit@1.1.1 based on (PR #194 & #200)"
