CHANGELOG.md, package.json, src/files/handler.js, src/index.js
SvelteKit `1.0.0-next.31` outputs `.cjs` so update the `require` of `handler.js`
Fix bug where destructure in `index.js.adpater()` failed due to missing default
Fixes: #5, #6
=> fix: .cjs and destructure of undefined

.husky/pre-commit, src/index.js
Investigating #6 uncovered two errors:
1. adapter logging was no longer advising the user how to setup their server
2. adapter configuration did not support an empty config as the object param did not have a default set so tried to destructure `undefined`
Fixes were included:
1. in #9 
2. is being fixed here
Fixes: #6 
This PR also fixes an issue with the `pre-commit` hook introduced in #10 It now adds to formatted code to the current commit.
=> fix: destructure of adapter config error

package-lock.json, package.json, src/files/handler.js, src/index.js
Inline the lib `@sveltejs/app-utils` into the `handler.js` and adapter entrypoint.
Fixes: #12
Despite this fixing the reported issue, the change to ESM and no CJS export from `@sveltejs/kit` means the error of ESM in a Cloud Function will show up in the when the `handler.js` executes it's require of `app.js` which itself `imports` ESM
=> fix: inline svelte-app-utils lib

tests/index.test.mjs
Improve the test reliability by detecting `__dirname` and using that to reference `tests/fixtures`
=> chore: improve test reliability

README.md, package.json, pnpm-lock.yaml, src/cli.js, src/files/index.cjs, src/utils.js, tests/fixtures/failures/cf_invalid_function_name.json, tests/index.test.mjs
The implementation here uses the same hack used in `adapter-vercel` and others to allow using `import` syntax in the CJS environment of Cloud Functions working around the issue of #16
=> feat: cloud function support

src/files/handler.js
Hi,
Thank you for a great library!
I change code in `src/files/handler.js`: use not query but searchParams.
`query` is undefined in URL, so `page.query` property in load function always null.
`routes/foo.svelte`
```ts
<script lang="ts" context="module">
import type { Load } from '@sveltejs/kit'
export async function load({ page, fetch }: Parameters<Load>[0]) {
const bar = page.query.get('xxx')  // If we access `http://***/?bar=123`, bar always null
}
...
</script>
```
=> fix: use searchParams in handler.js

.github/workflows/release.yml
The release workflow is broken on `main` because there is no `package.json.scripts.build` script as it was removed in #39. This change should have been made in #39 too.
=> fix: remove unused pnpm run build cmd from workflow

src/index.js
The SvelteKit template does not have a `dependencies` field in it's `package.json` which was required by the Cloud Run codepath. We will now add an empty `dependencies` field when it is not present.
Fixes: #34 
e2e tests should pick this up.
=> fix: handle empty deps when cloud run target

README.md, src/index.js, src/utils.js, tests/index.test.js
Dirs created by the adapter are expected to be relative to the `firebase.json` file, it is the root location. Currently this is not the case as noted in #33 
To resolve this we must:
Fixes: #33
=> fix: treat `firebase.json` as root dir for Firebase resources

README.md, package.json, pnpm-lock.yaml
In `0.6.1` we added the `preinstall` script that only allowed using `pnpm` which broke our Buildpack powered Run and Function build steps.
Fixes: #44 
Bumped kit to `@sveltejs/kit/1.0.0-next.101`
=> fix: allow any node package manager to install

README.md
`npx -y rimraf` causes an ambiguous error when not using the correct `npm` version. `-y` flag is new to `npm@7` however most users of this adapter will be using Node.js14 which ships `npm@6` so they will hit this error. 
Fixes: #58
=> docs: rm npx -y flag as its npm@7 only

src/index.js, src/utils.js, tests/index.test.js
- ensure the dirs for `svelte.config.js:kit.files.assets` is different from `firebase.json:hosting.public`
Fixes: #56
=> fix: static output dir differes from static source dirs

src/index.js, src/utils.js, tests/index.test.js
Ensure the Cloud Function runtime is set and is at least Node.js14 for compatibility with SvelteKit.
Fixes: #50
=> fix: ensure valid cloud function runtime version

src/index.js
Instruct users should also perform a `firebase deploy --only hosting` alongside their Cloud Run deployment as the new build may have produced new static assets, route manifests etc.
Fixes: #30
=> fix: instruct firebase deployment alongside Cloud Run

examples/functions_single_site/firebase.json, examples/functions_single_site/functions/.gitignore, examples/functions_single_site/functions/index.js, examples/nested_app_dirs/firebase.json, examples/nested_app_dirs/functions/.gitignore, examples/nested_app_dirs/functions/index.js, examples/run_single_site/.gitignore, examples/run_single_site/firebase.json, package.json, pnpm-lock.yaml, src/index.js, src/utils.js, tests/e2e-healthcheck.sh, tests/index.test.js
The adapter is meant to guide you through the setup, however the error messages and format/log-level are confusing users and making them feel like they made a mistake.
Fixes: #68 
~The error output was moved from the `msg` in `throw new Error(msg)` to `console.log()` calls, so a hash of the string input to `console.log()` was used in tests. This needs to be improved upon later.~
=> fix: improve guide & logging of adapter

package.json, pnpm-lock.yaml, src/files/handler.js, src/index.js
- These are the same as SvelteKit mins for Node.js 14 and 16
- Node.js 12 is **not** supported.
Fixes: #89
=> fix: specify minimum nodejs version in package.json

src/utils.js
This corrects the available Cloud Run regions when using Firebase Hosting Rewrites as per the documentation here - https://firebase.google.com/docs/hosting/full-config#rewrite-cloud-run-container
=> fix: valid cloud run region

src/files/handler.js, src/files/shims.js, src/index.js
Use [esbuild inject API](https://esbuild.github.io/api/#inject) as updated in official adapters in https://github.com/sveltejs/kit/pull/1822
>In particular, this guarantees:
> - Execution order before all user/kit code in build output
> - Properly polyfilled bindings for fetch etc
=> fix: use esbuild inject api to ensure exec order & polyfill

.github/workflows/test.yaml
This chore just cleans up the asdf-nodejs keyring config as it is not required anymore
=> ci: remove asdf-nodejs release-keyring

src/utils.js, tests/unit/src/utils.test.js
Allows use of `nodejs16` runtime environment.
Fixes: #128
=> fix: support nodejs16 env

src/index.js
SvelteKit templates no longer include the `--verbose` flag on the `svelte-kit build` `npm` script so users will not see the output unless we increase the log type used.
=> fix: output entrypoint code without verbose mode

src/files/firebase-to-svelte-kit.js, tests/unit/src/files/firebase-to-svelte-kit.test.js
Pass `rawBody:null` to SvelteKit `render(req)` function as per the changes in https://github.com/sveltejs/kit/pull/2299/files#diff-418712fdcdc80e8bf5cc0e519480d6bc0178a372c82aa3675dddd4870a5988a6R25
Fixes: #127 
As per https://github.com/firebase/firebase-functions/pull/959 the `firebase-functions.https.Request` type does not align with the upstream Functions Framework type and `req.rawBody` from Firebase is actually optional, so can be nullable, unlike the type information in VSCode indicates.
=> fix: pass null if no req.rawBody

src/files/entry.js, src/files/firebase-to-svelte-kit.js, src/files/shims.js, src/index.js
Update Adapter to support the latest version (next@303) of SvelteKit. 
Fixes: #153
No support for fancy features like route splitting.
Tested deployment on a live site with Firebase
Took some code from the other PR #157 so the author deserves credit.
- Uses Server instead of App
- Use the generated manifest of the builder instead of SvelteKit
- New way of using installFetch
- Remove the deprecated prerender call
- Thought process in long live video on [YouTube](https://www.youtube.com/watch?v=AhOWnouyfhE)
=> feat: Support for SvelteKit Next 303

.github/workflows/test.yaml, .tool-versions, CHANGELOG.md, README.md, package.json, pnpm-lock.yaml, src/files/entry.js, src/files/firebase-to-svelte-kit.js, src/files/shims.js, src/index.js, src/utils.js, tests/end-to-end/scaffold/functions/package.json, tests/end-to-end/scaffold/svelte.config.js, tests/end-to-end/test.bash, tests/integration/functions_single_site/svelte.config.js, tests/integration/integration-test.bash, tests/integration/nested_app_dirs/app/svelte.config.js, tests/integration/run_service_id/functions/index.js, tests/integration/run_service_id/svelte.config.js, tests/integration/test.bash, tests/unit/src/files/firebase-to-svelte-kit.test.js, tests/unit/src/utils.test.js
Update Adapter to support the latest version (next@329) of SvelteKit, thanks to [nielsvandermolen](https://github.com/nielsvandermolen) and [co3k](https://github.com/co3k) for their contributions!
Updates documentation.
Bumps package dependencies.
=> feat: upgrade to sveltekit 329

src/files/entry.js, src/index.js
Fixes headers not being passed from SvelteKit response object to Express Response object.
Fixes: #165
In order for the tests to successfully finish #173  has to be merged into main or this branch first.
=> fix: Pass rendered.headers to writeHead as object

.github/workflows/test.yaml, package.json, pnpm-lock.yaml, src/files/entry.js, tests/end-to-end/test.bash
`hooks.js` initialization has been moved to `Server.init`. Add code to initialize hooks in `entry.js`.
Fixes: #180 
The test end-to-end test script and test config matrix were modified to accommodate the new SvelteKit layout system.
=> fix(#180): Prepend `Server.init` before calling `Server.respond`

src/files/entry.js, src/files/firebase-to-svelte-kit.js, tests/end-to-end/test.bash
Fixes the "Cross-site POST form submissions are forbidden" error, by setting the correct header origin.
Fixes: End-to-end tests.
=> fix: cross-site POST requests

README.md, src/index.js, src/utils.js
`firebase init` command generates an array for `functions` field instead of an object inside the `firebase.json` file. This commit adds support to this configuration (getting the first element of the array) without removing the current implementation.
Fixes:
* #196
I couldn't find the documentation to this behavior but since I'm using the most recent version of the Firebase CLI, I guess this could be something the adapter should support.
=> fix: `firebase.json:functions` optionally as array

src/files/entry.js
when trying to build a Response with binary data or stream, it fails on server side deployment with no error but blank image or pdf the conversion from Response to ServerResponse manage binary data by using ArrayBuffer and convert it in a Buffer
=> fix: manage bynary data in response
